name: app_telemed_fila
description: "Um aplicativo de fila virtual para otimizar o tempo de espera."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (versões atualizadas para garantir compatibilidade)
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.1
  table_calendar: ^3.1.2
  cloud_functions: ^5.6.2 

  # Autenticação
  google_sign_in: ^6.2.1

  # Utilitários
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
