// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWjFVLgmpOfJDmkJd5hbtcI3rICGpq-nE',
    appId: '1:900023400699:web:b102c3af88d0e6fd0a185e',
    messagingSenderId: '900023400699',
    projectId: 'datatelemed',
    authDomain: 'datatelemed.firebaseapp.com',
    storageBucket: 'datatelemed.firebasestorage.app',
    measurementId: 'G-SLHVXCJKLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJkppbwKUWJ-YNM5kHGjC9Gu9w3opv-CM',
    appId: '1:900023400699:android:1089f7ca356c75870a185e',
    messagingSenderId: '900023400699',
    projectId: 'datatelemed',
    storageBucket: 'datatelemed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz-JP_DK9HpBStbOHxAv50rij6sUJYmek',
    appId: '1:900023400699:ios:a1d1c0100dd8e5870a185e',
    messagingSenderId: '900023400699',
    projectId: 'datatelemed',
    storageBucket: 'datatelemed.firebasestorage.app',
    iosBundleId: 'com.example.appTelemedFila',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz-JP_DK9HpBStbOHxAv50rij6sUJYmek',
    appId: '1:900023400699:ios:a1d1c0100dd8e5870a185e',
    messagingSenderId: '900023400699',
    projectId: 'datatelemed',
    storageBucket: 'datatelemed.firebasestorage.app',
    iosBundleId: 'com.example.appTelemedFila',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWjFVLgmpOfJDmkJd5hbtcI3rICGpq-nE',
    appId: '1:900023400699:web:30af06712d290fbe0a185e',
    messagingSenderId: '900023400699',
    projectId: 'datatelemed',
    authDomain: 'datatelemed.firebaseapp.com',
    storageBucket: 'datatelemed.firebasestorage.app',
    measurementId: 'G-16CXHZVQBB',
  );
}
